// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Achievements.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class НастройкаПравилПодсчетаРейтингаОтПолученныхОценокFeature : object, Xunit.IClassFixture<НастройкаПравилПодсчетаРейтингаОтПолученныхОценокFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SetUpGradeRules.feature"
#line hidden
        
        public НастройкаПравилПодсчетаРейтингаОтПолученныхОценокFeature(НастройкаПравилПодсчетаРейтингаОтПолученныхОценокFeature.FixtureData fixtureData, Achievements_Specs_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Настройка правил подсчета рейтинга от полученных оценок", "Настройка правил подсчета рейтинга доступна только для взрослых", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Взрослые могут настраивать правило подсчета рейтинга за полученные ребенком хорош" +
            "ие оценки")]
        [Xunit.TraitAttribute("FeatureTitle", "Настройка правил подсчета рейтинга от полученных оценок")]
        [Xunit.TraitAttribute("Description", "Взрослые могут настраивать правило подсчета рейтинга за полученные ребенком хорош" +
            "ие оценки")]
        public virtual void ВзрослыеМогутНастраиватьПравилоПодсчетаРейтингаЗаПолученныеРебенкомХорошиеОценки()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Взрослые могут настраивать правило подсчета рейтинга за полученные ребенком хорош" +
                    "ие оценки", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Phone",
                            "Name",
                            "Adult"});
                table19.AddRow(new string[] {
                            "father@family.com",
                            "+79180000001",
                            "Папа",
                            "да"});
                table19.AddRow(new string[] {
                            "son@family.com",
                            "+79180000004",
                            "Сын",
                            "нет"});
#line 6
  testRunner.Given("Семья из", ((string)(null)), table19, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "Условие изменения рейтинга",
                            "Изменеие в баллах"});
                table20.AddRow(new string[] {
                            "Ребенок просрочил задачу",
                            "-5"});
                table20.AddRow(new string[] {
                            "Ребенок выполнил задачу",
                            "+10"});
                table20.AddRow(new string[] {
                            "Ребенок получил оценку 2",
                            "-10"});
                table20.AddRow(new string[] {
                            "Ребенок получил оценку 3",
                            "+0"});
                table20.AddRow(new string[] {
                            "Ребенок получил оценку 4",
                            "+5"});
                table20.AddRow(new string[] {
                            "Ребенок получил оценку 5",
                            "+15"});
#line 10
  testRunner.And("Правила", ((string)(null)), table20, "And ");
#line hidden
#line 18
  testRunner.And("в систему вошел Папа", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
  testRunner.When("Пользователь меняет правило подсчета при получении ребенком оценки 4(+10)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
  testRunner.And("Пользователь просматривает правила подсчета рейтинга", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
  testRunner.Then("В правилах указано, что за получение оценки 4 ребенку начисляется 10 баллов", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Взрослые могут настраивать правило подсчета рейтинга за полученные ребенком плохи" +
            "е оценки")]
        [Xunit.TraitAttribute("FeatureTitle", "Настройка правил подсчета рейтинга от полученных оценок")]
        [Xunit.TraitAttribute("Description", "Взрослые могут настраивать правило подсчета рейтинга за полученные ребенком плохи" +
            "е оценки")]
        public virtual void ВзрослыеМогутНастраиватьПравилоПодсчетаРейтингаЗаПолученныеРебенкомПлохиеОценки()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Взрослые могут настраивать правило подсчета рейтинга за полученные ребенком плохи" +
                    "е оценки", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 23
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Phone",
                            "Name",
                            "Adult"});
                table21.AddRow(new string[] {
                            "father@family.com",
                            "+79180000001",
                            "Папа",
                            "да"});
                table21.AddRow(new string[] {
                            "son@family.com",
                            "+79180000004",
                            "Сын",
                            "нет"});
#line 24
  testRunner.Given("Семья из", ((string)(null)), table21, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "Условие изменения рейтинга",
                            "Изменеие в баллах"});
                table22.AddRow(new string[] {
                            "Ребенок просрочил задачу",
                            "-5"});
                table22.AddRow(new string[] {
                            "Ребенок выполнил задачу",
                            "+10"});
                table22.AddRow(new string[] {
                            "Ребенок получил оценку 2",
                            "-10"});
                table22.AddRow(new string[] {
                            "Ребенок получил оценку 3",
                            "+0"});
                table22.AddRow(new string[] {
                            "Ребенок получил оценку 4",
                            "+5"});
                table22.AddRow(new string[] {
                            "Ребенок получил оценку 5",
                            "+15"});
#line 28
  testRunner.And("Правила", ((string)(null)), table22, "And ");
#line hidden
#line 36
  testRunner.And("в систему вошел Папа", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 37
  testRunner.When("Пользователь меняет правило подсчета при получении ребенком оценки 3(-5)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 38
  testRunner.And("Пользователь просматривает правила подсчета рейтинга", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 39
  testRunner.Then("В правилах указано, что за получение оценки 3 у ребенка снимается 5 баллов", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ребенок не может настраивать правило подсчета рейтинга за полученные ребенком оце" +
            "нки")]
        [Xunit.TraitAttribute("FeatureTitle", "Настройка правил подсчета рейтинга от полученных оценок")]
        [Xunit.TraitAttribute("Description", "Ребенок не может настраивать правило подсчета рейтинга за полученные ребенком оце" +
            "нки")]
        public virtual void РебенокНеМожетНастраиватьПравилоПодсчетаРейтингаЗаПолученныеРебенкомОценки()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ребенок не может настраивать правило подсчета рейтинга за полученные ребенком оце" +
                    "нки", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 41
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "Email",
                            "Phone",
                            "Name",
                            "Adult"});
                table23.AddRow(new string[] {
                            "father@family.com",
                            "+79180000001",
                            "Папа",
                            "да"});
                table23.AddRow(new string[] {
                            "son@family.com",
                            "+79180000004",
                            "Сын",
                            "нет"});
#line 42
  testRunner.Given("Семья из", ((string)(null)), table23, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "Условие изменения рейтинга",
                            "Изменеие в баллах"});
                table24.AddRow(new string[] {
                            "Ребенок просрочил задачу",
                            "-5"});
                table24.AddRow(new string[] {
                            "Ребенок выполнил задачу",
                            "+10"});
                table24.AddRow(new string[] {
                            "Ребенок получил оценку 2",
                            "-10"});
                table24.AddRow(new string[] {
                            "Ребенок получил оценку 3",
                            "+0"});
                table24.AddRow(new string[] {
                            "Ребенок получил оценку 4",
                            "+5"});
                table24.AddRow(new string[] {
                            "Ребенок получил оценку 5",
                            "+15"});
#line 46
  testRunner.And("Правила", ((string)(null)), table24, "And ");
#line hidden
#line 54
  testRunner.And("в систему вошел Сын", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 55
  testRunner.When("Пользователь меняет правило подсчета при получении ребенком оценки 2(+100)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 56
  testRunner.And("Пользователь просматривает правила подсчета рейтинга", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 57
  testRunner.Then("В правилах указано, что за получение оценки 2 у ребенка снимается 10 баллов", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                НастройкаПравилПодсчетаРейтингаОтПолученныхОценокFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                НастройкаПравилПодсчетаРейтингаОтПолученныхОценокFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
